# SonarQube / SonarCloud Project Configuration
sonar.projectKey=Vikas-TK_CI-CD
sonar.organization=vikas-tk
sonar.projectName=Hospital Management System
sonar.projectVersion=1.0.0

# Source & Test paths
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Language
sonar.language=py
sonar.python.version=3.10, 3.11, 3.12

# Coverage & Test reports
sonar.python.coverage.reportPaths=test-results/coverage.xml
sonar.python.xunit.reportPath=test-results/junit.xml

# Exclusions
sonar.exclusions=migrations/**, tests/**, app/static/**, **/*.html, **/*.css
